name: Build and deliver containers

on: push

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: npm build deliver formula1-frontend container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build --build-arg VITE_API_URL="https://transferapi.janpeterdhalle.com" -t ${{ secrets.DOCKER_USER }}/jp-transfer-ui:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/jp-transfer-ui:latest

